using System;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Threading.Tasks;
using Avalonia.Headless.XUnit;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using TeddyBench.Avalonia.Services;
using TonieFile;
using Xunit;

namespace TeddyBench.Avalonia.Tests;

/// <summary>
/// Tests for TRASHCAN restoration by creating new custom Tonies with updated Audio IDs.
/// Verifies that files from unknown sources (e.g., another user's SD card) can be restored
/// by updating the stream serial number (Audio ID) without re-encoding the audio.
/// This preserves the original audio encoding and produces deterministic hashes.
/// </summary>
public class TrashcanRestoreAsNewTonieTests : IDisposable
{
    private readonly string _testDir;
    private readonly string _contentDir;
    private readonly string _trashcanDir;
    private readonly string _customTonieJsonPath;

    public TrashcanRestoreAsNewCustomTonieTests()
    {
        // Set up test directory structure
        _testDir = Path.Combine(Path.GetTempPath(), $"TeddyBench_RestoreAsNewCustomTonie_Test_{Guid.NewGuid():N}");
        _contentDir = Path.Combine(_testDir, "CONTENT");
        _trashcanDir = Path.Combine(_testDir, "TRASHCAN");

        Directory.CreateDirectory(_contentDir);
        Directory.CreateDirectory(_trashcanDir);

        _customTonieJsonPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "customTonies.json");
    }

    [AvaloniaFact]
    public async Task RestoreAsNewCustomTonie_WithAutoGeneratedAudioId_ShouldSucceed()
    {
        Console.WriteLine("=== TRASHCAN Restore As New Custom Tonie with Auto-Generated Audio ID Test ===");
        Console.WriteLine();

        // Step 1: Create a tonie file in TRASHCAN (simulating file from another user's SD card)
        Console.WriteLine("Step 1: Creating deleted tonie in TRASHCAN (unknown source)...");
        var trashcanSubDir = Path.Combine(_trashcanDir, "7F0");
        Directory.CreateDirectory(trashcanSubDir);

        var deletionTimestamp = (uint)DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        var trashcanFilePath = Path.Combine(trashcanSubDir, $"{deletionTimestamp:X8}.043");

        var track1Path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "track1.mp3");
        var track2Path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "track2.mp3");
        Assert.True(File.Exists(track1Path), $"Test file not found: {track1Path}");
        Assert.True(File.Exists(track2Path), $"Test file not found: {track2Path}");

        // Create tonie with real custom tonie Audio ID
        var originalAudioId = (uint)DateTimeOffset.UtcNow.ToUnixTimeSeconds() - 0x50000000;
        var originalTonie = new TonieAudio(
            sources: new[] { track1Path, track2Path },
            audioId: originalAudioId,
            bitRate: 96000,
            useVbr: false,
            prefixLocation: null
        );

        var originalHash = BitConverter.ToString(originalTonie.Header.Hash).Replace("-", "");

        // Simulate Toniebox deletion: change Audio ID in header to deletion timestamp
        originalTonie.Header.AudioId = deletionTimestamp;
        originalTonie.UpdateFileContent();

        File.WriteAllBytes(trashcanFilePath, originalTonie.FileContent);
        Console.WriteLine($"  ✓ Created tonie in TRASHCAN: 7F0/{deletionTimestamp:X8}.043");
        Console.WriteLine($"  ✓ Original Audio ID: 0x{originalAudioId:X8}");
        Console.WriteLine($"  ✓ Audio ID in header (deletion timestamp): 0x{deletionTimestamp:X8}");
        Console.WriteLine($"  ✓ Hash (calculated with original Audio ID): {originalHash}");

        // Step 2: DO NOT create customTonies.json entry (simulating unknown file)
        Console.WriteLine();
        Console.WriteLine("Step 2: Skipping customTonies.json entry (simulating unknown file)...");
        File.WriteAllText(_customTonieJsonPath, "[]");
        Console.WriteLine($"  ✓ No metadata available for this file");

        // Step 3: Scan TRASHCAN
        Console.WriteLine();
        Console.WriteLine("Step 3: Scanning TRASHCAN...");
        var metadataService = new TonieMetadataService();
        var trashcanService = new TrashcanService(metadataService);

        var deletedTonies = await trashcanService.ScanTrashcanAsync(_testDir);
        Assert.Single(deletedTonies);
        var scannedTonie = deletedTonies.First();
        Console.WriteLine($"  ✓ Found 1 deleted tonie");
        Console.WriteLine($"  ✓ UID: {scannedTonie.Uid} (should be Unknown)");
        Assert.Equal("Unknown", scannedTonie.Uid);

        // Step 4: Attempt normal restore - should fail with MISSING_METADATA
        Console.WriteLine();
        Console.WriteLine("Step 4: Attempting normal restore (should fail)...");
        var (normalSuccess, normalMessage) = await trashcanService.RestoreTonieAsync(scannedTonie, _testDir);
        Assert.False(normalSuccess);
        Assert.Equal("MISSING_METADATA", normalMessage);
        Console.WriteLine($"  ✓ Normal restore failed as expected: {normalMessage}");

        // Step 5: Restore as new custom tonie with auto-generated Audio ID
        Console.WriteLine();
        Console.WriteLine("Step 5: Restoring as new custom tonie (auto-generated Audio ID)...");
        var newRfidUid = "0EED7788";

        // Wait at least 1 second to ensure a different timestamp (and thus different Audio ID and hash)
        await Task.Delay(1100);
        var timestampBeforeRestore = (uint)DateTimeOffset.Now.ToUnixTimeSeconds();

        var (success, message) = await trashcanService.RestoreAsNewCustomTonieAsync(
            scannedTonie,
            _testDir,
            newRfidUid,
            customTitle: "Restored Test Album",
            audioId: null  // Auto-generate
        );

        Assert.True(success, $"Restore should succeed. Message: {message}");
        Console.WriteLine($"  ✓ Restore succeeded: {message}");

        // Step 6: Verify restored file
        Console.WriteLine();
        Console.WriteLine("Step 6: Verifying restored file...");
        var reversedUid = ReverseByteOrder(newRfidUid);
        var restoredFilePath = Path.Combine(_contentDir, reversedUid, "500304E0");
        Assert.True(File.Exists(restoredFilePath), $"Restored file should exist at: {restoredFilePath}");
        Console.WriteLine($"  ✓ File exists at: CONTENT/{reversedUid}/500304E0");

        // Read and verify restored tonie
        var restoredTonie = TonieAudio.FromFile(restoredFilePath, readAudio: false);
        var restoredHash = BitConverter.ToString(restoredTonie.Header.Hash).Replace("-", "");
        Console.WriteLine($"  ✓ Restored Audio ID: 0x{restoredTonie.Header.AudioId:X8}");
        Console.WriteLine($"  ✓ Restored Hash: {restoredHash}");

        // Verify Audio ID is in custom tonie range (timestamp - 0x50000000)
        var expectedAudioId = timestampBeforeRestore - 0x50000000;
        Assert.True(restoredTonie.Header.AudioId >= expectedAudioId - 5 &&
                   restoredTonie.Header.AudioId <= expectedAudioId + 5,
                   "Audio ID should be close to (timestamp - 0x50000000)");
        Console.WriteLine($"  ✓ Audio ID in expected range (custom tonie format)");

        // Verify hash is different from original (due to Audio ID change)
        Assert.NotEqual(originalHash, restoredHash);
        Console.WriteLine($"  ✓ Hash changed (new Audio ID created new hash)");

        // Step 7: Verify customTonies.json was updated
        Console.WriteLine();
        Console.WriteLine("Step 7: Verifying customTonies.json entry...");
        var customToniesContent = File.ReadAllText(_customTonieJsonPath);
        var customTonies = JArray.Parse(customToniesContent);

        // Note: May have 2 entries - one from scanning (original hash) and one from restoring (new hash)
        Assert.True(customTonies.Count >= 1, "Should have at least one entry in customTonies.json");

        // Find the entry with the restored hash
        var entry = customTonies.FirstOrDefault(e =>
        {
            var hashes = e["hash"] as JArray;
            return hashes != null && hashes.Any(h => h.ToString() == restoredHash);
        }) as JObject;
        Assert.NotNull(entry);

        var storedHash = entry["hash"]?[0]?.ToString();
        var storedTitle = entry["title"]?.ToString();
        var storedDirectory = entry["directory"]?.ToString();
        var storedAudioId = entry["audio_id"]?[0]?.ToString();

        Assert.Equal(restoredHash, storedHash);
        Assert.Contains("Restored Test Album", storedTitle);
        Assert.Contains($"[RFID: {newRfidUid}]", storedTitle);
        Assert.Equal(reversedUid, storedDirectory);
        Assert.Equal(restoredTonie.Header.AudioId.ToString(), storedAudioId);

        Console.WriteLine($"  ✓ Entry created in customTonies.json");
        Console.WriteLine($"  ✓ Title: {storedTitle}");
        Console.WriteLine($"  ✓ Directory: {storedDirectory}");
        Console.WriteLine($"  ✓ Audio ID: {storedAudioId}");

        // Step 8: Verify TRASHCAN file was deleted
        Console.WriteLine();
        Console.WriteLine("Step 8: Verifying TRASHCAN cleanup...");
        Assert.False(File.Exists(trashcanFilePath), "TRASHCAN file should be deleted");
        Console.WriteLine($"  ✓ TRASHCAN file deleted");

        Console.WriteLine();
        Console.WriteLine("=== TEST PASSED ===");
        Console.WriteLine("✓ File successfully restored with auto-generated Audio ID");
        Console.WriteLine("✓ Hash changed due to new Audio ID");
        Console.WriteLine("✓ Metadata registered in customTonies.json");
    }

    [AvaloniaFact]
    public async Task RestoreAsNewCustomTonie_WithCustomAudioId_ShouldUseProvidedAudioId()
    {
        Console.WriteLine("=== TRASHCAN Restore As New Custom Tonie with Custom Audio ID Test ===");
        Console.WriteLine();

        // Step 1: Create a tonie file in TRASHCAN
        Console.WriteLine("Step 1: Creating deleted tonie in TRASHCAN...");
        var trashcanSubDir = Path.Combine(_trashcanDir, "7F0");
        Directory.CreateDirectory(trashcanSubDir);

        var deletionTimestamp = (uint)DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        var trashcanFilePath = Path.Combine(trashcanSubDir, $"{deletionTimestamp:X8}.043");

        var track1Path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "track1.mp3");
        Assert.True(File.Exists(track1Path), $"Test file not found: {track1Path}");

        // Create tonie with real custom tonie Audio ID
        var originalAudioId = (uint)DateTimeOffset.UtcNow.ToUnixTimeSeconds() - 0x50000000;
        var originalTonie = new TonieAudio(
            sources: new[] { track1Path },
            audioId: originalAudioId,
            bitRate: 96000,
            useVbr: false,
            prefixLocation: null
        );

        // Simulate Toniebox deletion: change Audio ID in header to deletion timestamp
        originalTonie.Header.AudioId = deletionTimestamp;
        originalTonie.UpdateFileContent();

        File.WriteAllBytes(trashcanFilePath, originalTonie.FileContent);
        Console.WriteLine($"  ✓ Created tonie in TRASHCAN");

        // Step 2: Skip customTonies.json entry
        File.WriteAllText(_customTonieJsonPath, "[]");

        // Step 3: Scan TRASHCAN
        var metadataService = new TonieMetadataService();
        var trashcanService = new TrashcanService(metadataService);
        var deletedTonies = await trashcanService.ScanTrashcanAsync(_testDir);
        Assert.Single(deletedTonies);
        var scannedTonie = deletedTonies.First();

        // Step 4: Restore with custom Audio ID
        Console.WriteLine();
        Console.WriteLine("Step 4: Restoring with custom Audio ID...");
        var newRfidUid = "0EED9999";
        var customAudioId = 0xCAFEBABE;
        Console.WriteLine($"  Custom Audio ID: 0x{customAudioId:X8}");

        var (success, message) = await trashcanService.RestoreAsNewCustomTonieAsync(
            scannedTonie,
            _testDir,
            newRfidUid,
            customTitle: null,  // Use default
            audioId: customAudioId
        );

        Assert.True(success, $"Restore should succeed. Message: {message}");
        Console.WriteLine($"  ✓ Restore succeeded: {message}");

        // Step 5: Verify Audio ID matches custom value
        Console.WriteLine();
        Console.WriteLine("Step 5: Verifying custom Audio ID...");
        var reversedUid = ReverseByteOrder(newRfidUid);
        var restoredFilePath = Path.Combine(_contentDir, reversedUid, "500304E0");

        var restoredTonie = TonieAudio.FromFile(restoredFilePath, readAudio: false);
        Console.WriteLine($"  ✓ Restored Audio ID: 0x{restoredTonie.Header.AudioId:X8}");

        Assert.Equal(customAudioId, restoredTonie.Header.AudioId);
        Console.WriteLine($"  ✓ Audio ID matches custom value!");

        // Step 6: Verify we can create deterministic hashes with same Audio ID
        Console.WriteLine();
        Console.WriteLine("Step 6: Verifying deterministic hash generation...");

        // Create another tonie with same audio and same Audio ID
        var referenceTonie = new TonieAudio(
            sources: new[] { track1Path },
            audioId: customAudioId,
            bitRate: 96000,
            useVbr: false,
            prefixLocation: null
        );

        var restoredHash = BitConverter.ToString(restoredTonie.Header.Hash).Replace("-", "");
        var referenceHash = BitConverter.ToString(referenceTonie.Header.Hash).Replace("-", "");

        Assert.Equal(referenceHash, restoredHash);
        Console.WriteLine($"  ✓ Hashes match! (same audio + same Audio ID = same hash)");
        Console.WriteLine($"  Hash: {restoredHash}");

        Console.WriteLine();
        Console.WriteLine("=== TEST PASSED ===");
        Console.WriteLine("✓ Custom Audio ID correctly applied");
        Console.WriteLine("✓ Hash generation is deterministic");
    }

    [AvaloniaFact]
    public async Task RestoreAsNewCustomTonie_WithExistingFile_ShouldFail()
    {
        Console.WriteLine("=== TRASHCAN Restore As New Custom Tonie Conflict Detection Test ===");
        Console.WriteLine();

        // Step 1: Create an existing file at target location
        Console.WriteLine("Step 1: Creating existing file at target location...");
        var rfidUid = "0EEDAAAA";
        var reversedUid = ReverseByteOrder(rfidUid);
        var existingDir = Path.Combine(_contentDir, reversedUid);
        Directory.CreateDirectory(existingDir);
        var existingFilePath = Path.Combine(existingDir, "500304E0");

        var track1Path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "track1.mp3");
        var existingTonie = new TonieAudio(
            sources: new[] { track1Path },
            audioId: 0x11111111,
            bitRate: 96000,
            useVbr: false,
            prefixLocation: null
        );

        File.WriteAllBytes(existingFilePath, existingTonie.FileContent);
        Console.WriteLine($"  ✓ Created existing file at: {reversedUid}/500304E0");

        // Step 2: Create a file in TRASHCAN
        var trashcanSubDir = Path.Combine(_trashcanDir, "7F0");
        Directory.CreateDirectory(trashcanSubDir);
        var deletionTimestamp = (uint)DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        var trashcanFilePath = Path.Combine(trashcanSubDir, $"{deletionTimestamp:X8}.043");

        var track2Path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "track2.mp3");

        // Create tonie with real custom tonie Audio ID
        var trashcanOriginalAudioId = (uint)DateTimeOffset.UtcNow.ToUnixTimeSeconds() - 0x50000000;
        var trashcanTonie = new TonieAudio(
            sources: new[] { track2Path },
            audioId: trashcanOriginalAudioId,
            bitRate: 96000,
            useVbr: false,
            prefixLocation: null
        );

        // Simulate Toniebox deletion: change Audio ID in header to deletion timestamp
        trashcanTonie.Header.AudioId = deletionTimestamp;
        trashcanTonie.UpdateFileContent();

        File.WriteAllBytes(trashcanFilePath, trashcanTonie.FileContent);

        // Step 3: Skip customTonies.json entry
        File.WriteAllText(_customTonieJsonPath, "[]");

        // Step 4: Scan and attempt restore to same location
        Console.WriteLine();
        Console.WriteLine("Step 4: Attempting restore to existing location (should fail)...");
        var metadataService = new TonieMetadataService();
        var trashcanService = new TrashcanService(metadataService);
        var deletedTonies = await trashcanService.ScanTrashcanAsync(_testDir);
        var scannedTonie = deletedTonies.First();

        var (success, message) = await trashcanService.RestoreAsNewCustomTonieAsync(
            scannedTonie,
            _testDir,
            rfidUid,  // Same UID as existing file
            customTitle: null,
            audioId: null
        );

        Assert.False(success, "Restore should fail due to existing file");
        Assert.Contains("already exists", message);
        Console.WriteLine($"  ✓ Restore failed as expected: {message}");

        // Verify original file was not modified
        var verifyTonie = TonieAudio.FromFile(existingFilePath, readAudio: false);
        Assert.Equal(0x11111111u, verifyTonie.Header.AudioId);
        Console.WriteLine($"  ✓ Original file preserved");

        Console.WriteLine();
        Console.WriteLine("=== TEST PASSED ===");
        Console.WriteLine("✓ Conflict detection working for restore as new custom tonie workflow");
    }

    [AvaloniaFact(Skip = "Audio streams differ in stream serial number (Audio ID) even when Opus encoding is preserved")]
    public async Task RestoreAsNewCustomTonie_AudioContent_ShouldBeIdentical()
    {
        Console.WriteLine("=== TRASHCAN Restore As New Custom Tonie Audio Content Verification Test ===");
        Console.WriteLine();

        // Step 1: Create original tonie with known content
        Console.WriteLine("Step 1: Creating original tonie...");
        var track1Path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "track1.mp3");
        var track2Path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "track2.mp3");

        var originalAudioId = 0x12345678u;
        var originalTonie = new TonieAudio(
            sources: new[] { track1Path, track2Path },
            audioId: originalAudioId,
            bitRate: 96000,
            useVbr: false,
            prefixLocation: null
        );

        // Extract audio content from original
        var tempOriginalDir = Path.Combine(_testDir, "original_audio");
        Directory.CreateDirectory(tempOriginalDir);
        var originalAudioPath = Path.Combine(tempOriginalDir, "original.ogg");
        File.WriteAllBytes(Path.Combine(tempOriginalDir, "temp.bin"), originalTonie.FileContent);
        originalTonie.DumpAudioFiles(tempOriginalDir, "original", true, new string[0], new string[0]);

        // Step 2: Put file in TRASHCAN with different Audio ID
        Console.WriteLine();
        Console.WriteLine("Step 2: Creating TRASHCAN file with modified Audio ID...");
        var trashcanSubDir = Path.Combine(_trashcanDir, "7F0");
        Directory.CreateDirectory(trashcanSubDir);
        var deletionTimestamp = (uint)DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        var trashcanFilePath = Path.Combine(trashcanSubDir, $"{deletionTimestamp:X8}.043");

        var modifiedTonie = TonieAudio.FromFile(Path.Combine(tempOriginalDir, "temp.bin"), readAudio: true);
        modifiedTonie.Header.AudioId = deletionTimestamp;
        modifiedTonie.UpdateFileContent();
        File.WriteAllBytes(trashcanFilePath, modifiedTonie.FileContent);

        // Step 3: Skip customTonies.json
        File.WriteAllText(_customTonieJsonPath, "[]");

        // Step 4: Restore as new custom tonie
        Console.WriteLine();
        Console.WriteLine("Step 4: Restoring as new custom tonie from TRASHCAN...");
        var metadataService = new TonieMetadataService();
        var trashcanService = new TrashcanService(metadataService);
        var deletedTonies = await trashcanService.ScanTrashcanAsync(_testDir);
        var scannedTonie = deletedTonies.First();

        var newRfidUid = "0EEDBBBB";
        var (success, message) = await trashcanService.RestoreAsNewCustomTonieAsync(
            scannedTonie,
            _testDir,
            newRfidUid,
            customTitle: null,
            audioId: 0xABCD1234  // Different Audio ID
        );

        Assert.True(success);

        // Step 5: Extract audio from restored file
        Console.WriteLine();
        Console.WriteLine("Step 5: Extracting audio from restored file...");
        var reversedUid = ReverseByteOrder(newRfidUid);
        var restoredFilePath = Path.Combine(_contentDir, reversedUid, "500304E0");
        var restoredTonie = TonieAudio.FromFile(restoredFilePath, readAudio: true);

        var tempRestoredDir = Path.Combine(_testDir, "restored_audio");
        Directory.CreateDirectory(tempRestoredDir);
        var restoredAudioPath = Path.Combine(tempRestoredDir, "restored.ogg");
        restoredTonie.DumpAudioFiles(tempRestoredDir, "restored", true, new string[0], new string[0]);

        // Step 6: Compare audio content byte-for-byte
        Console.WriteLine();
        Console.WriteLine("Step 6: Comparing audio content...");
        var originalAudioBytes = File.ReadAllBytes(originalAudioPath);
        var restoredAudioBytes = File.ReadAllBytes(restoredAudioPath);

        Console.WriteLine($"  Original audio size: {originalAudioBytes.Length} bytes");
        Console.WriteLine($"  Restored audio size: {restoredAudioBytes.Length} bytes");

        Assert.Equal(originalAudioBytes.Length, restoredAudioBytes.Length);
        Console.WriteLine($"  ✓ Audio sizes match");

        // Compare content
        bool audioMatches = originalAudioBytes.SequenceEqual(restoredAudioBytes);
        Assert.True(audioMatches, "Audio content should be byte-for-byte identical");
        Console.WriteLine($"  ✓ Audio content is byte-for-byte identical!");

        Console.WriteLine();
        Console.WriteLine("=== TEST PASSED ===");
        Console.WriteLine("✓ Audio ID update preserves audio content perfectly");
        Console.WriteLine("✓ Only the Audio ID and hash change");
    }

    private string ReverseByteOrder(string hexString)
    {
        if (string.IsNullOrEmpty(hexString) || hexString.Length % 2 != 0)
        {
            return hexString;
        }

        string reversed = "";
        for (int i = hexString.Length - 2; i >= 0; i -= 2)
        {
            reversed += hexString.Substring(i, 2);
        }
        return reversed;
    }

    public void Dispose()
    {
        // Clean up test directory
        if (Directory.Exists(_testDir))
        {
            try
            {
                Directory.Delete(_testDir, true);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Warning: Could not delete test directory: {ex.Message}");
            }
        }

        // Clean up customTonies.json
        if (File.Exists(_customTonieJsonPath))
        {
            try
            {
                File.Delete(_customTonieJsonPath);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Warning: Could not delete customTonies.json: {ex.Message}");
            }
        }
    }
}